spring:
  datasource:
    url: jdbc:tc:mysql:8.0.28:///test?TC_DAEMON=true
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
